### ISSUE TITLE
Enhancement: The ability for admins to manually create teams

### ISSUE THREAD

**Issue by ShyftXero** [deckar01/CTFd#6]
This would be beneficial for staging events or in training environments where account info is distributed to participants before the event.

Lots of the registration code could be reused to this end.

**Comment by deckar01** [comment]
This was implemented in https://github.com/deckar01/CTFd/commit/19a240f43aa61f1a7b5002c4c5513ca7f72a8933.

I fixed [5 bugs](https://github.com/deckar01/CTFd/compare/11ed3a70140894bdd450070ea23cbb775f096f7d...25e06fe3681607ec04f11e343196d8ed6cce778a) and made [1 security enhancement](https://github.com/deckar01/CTFd/commit/11ed3a70140894bdd450070ea23cbb775f096f7d) in the process.

<img width="1396" alt="screen shot 2017-10-12 at 8 41 47 pm" src="https://user-images.githubusercontent.com/3108007/31526660-dd20a46e-af8d-11e7-9b63-3269dbdab810.png">

<img width="1306" alt="screen shot 2017-10-12 at 8 42 00 pm" src="https://user-images.githubusercontent.com/3108007/31526659-dd082272-af8d-11e7-9e5d-e96250a59b51.png">
