### ISSUE TITLE
Enhancement: The ability to "pause" the CTF

### ISSUE THREAD

**Issue by ShyftXero** [deckar01/CTFd#8]
someone mentioned this as a feature request in the upstream issues. 

This would be useful for our event because we have an 8 hour period where the challenges are going to be off-line. At least the scoreboard and the ability to submit flags will be. 

Rather than shuffling around the ctf end times, could we implement a "pause" and "unpause" button. under config-> CTF time

I believe this would be easy enough to implement via javascript.
we could manipulate the start time to be 100 years in the future for Pause and yesterday (whatever that is ) for Unpause. 

Is it worth messing with?

**Comment by deckar01** [comment]
This was implemented in https://github.com/deckar01/CTFd/commit/9229eec9b65c1ddc1bfecb27f5c0fcdc4442e633.

I added a "paused" config variable and made a button in the admin config that toggles it. I added logic for this flag to the "ctftime" check and added custom messaging where it was needed.

Admin View:

<img width="858" alt="screen shot 2017-10-13 at 9 15 41 pm" src="https://user-images.githubusercontent.com/3108007/31571817-7be4a380-b05f-11e7-899e-d9e5625902f9.png">

<img width="851" alt="screen shot 2017-10-13 at 9 15 20 pm" src="https://user-images.githubusercontent.com/3108007/31571818-7bf79918-b05f-11e7-892c-5a57c9078629.png">

If you try to load the challenges page:

![screen shot 2017-10-13 at 9 31 01 pm](https://user-images.githubusercontent.com/3108007/31571816-7bd09f20-b05f-11e7-8d7a-64ed88940ce5.png)

When the challenges page refreshes (automatically):

![screen shot 2017-10-13 at 9 14 50 pm](https://user-images.githubusercontent.com/3108007/31571819-7c0a0d5a-b05f-11e7-9460-c3699238e62b.png)
